name: fun4-frontend
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      
  jobs:
    ci:
      runs-on: ubuntu-latest
      container:
        image: node
      steps:
        - name: Git Checkout
          uses: actions/checkout@v1'
        - name: Install
          run: npm install
        - name: Test
          run: npm test
    cd:
      runs-on: ubuntu-latest
      needs: ci
      
      steps:
        - name: Git Checkout
          uses: actions/checkout@v1
        - name: Docker Login
          run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        - name: Build
          run: docker build -t fun4-frontend .
        - name: Tags
          run: |
            docker tag fun4-frontend ${{ secrets.DOCKER_USER }}/fun4-frontend:${{ github.sha }}
            docker tag fun4-frontend ${{ secrets.DOCKER_USER }}/fun4-frontend:latest
        - name: Push
          run: |
            docker push ${{ secrets.DOCKER_USER }}/front:${{ github.sha }}
            docker push ${{ secrets.DOCKER_USER }}/front:latest
